version: "3.8"
services:

  edc:
    container_name: edc
    image: ghcr.io/sovity/broker-extension:main
    environment:
      IDS_WEBHOOK_ADDRESS: http://edc:8282
      EDC_IDS_ID: urn:connector:catalog-transfer-edc
      EDC_IDS_CURATOR: https://example.com
      EDC_IDS_MAINTAINER: https://example.com
      EDC_CONNECTOR_NAME: EDC-Connector
      EDC_HOSTNAME: company1
      EDC_VAULT: /resources/vault/edc/vault.properties
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      UPDATE_INTERVAL_IN_SECONDS: 5
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,x-api-key"
      EDC_BROKER_BASE_URL: https://broker.test.mobility-dataspace.eu
      EDC_KEYSTORE: /resources/vault/edc/keystore.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_PUBLIC_KEY_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID:
      EDC_OAUTH_TOKEN_URL: https://daps.test.mobility-dataspace.eu/token
      EDC_OAUTH_PROVIDER_JWKS_URL: https://daps.test.mobility-dataspace.eu/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
    volumes:
      - ../../resources:/resources

volumes:
  db: