name: Add pull request to project action

on:
  pull_request:

jobs:
  add_pullrequest_to_project:
    if: github.actor != 'dependabot' && github.actor != 'sovitybot' # ignore PRs from bots
    name: add_pullrequest_to_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/sovity/projects/21
          github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
          labeled: area/dependency
          label-operator: NOT
