name: Release Docs Zip File

on:
  release:
    types: [ published ]

env:
  IMAGE_NAME_BASE: ${{ github.repository_owner }}

jobs:
  add_docs_zip_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Archive deployment-relevant documentation.
        run: |
          ARCHIVE_FILE_NAME="broker-server-release-${GITHUB_REF#refs/tags/v}-deployment-docs.zip"
          echo "ARCHIVE_FILE_NAME=$ARCHIVE_FILE_NAME" >> $GITHUB_ENV
          zip -r -q $ARCHIVE_FILE_NAME README.md CHANGELOG.md docker-compose.yaml .env connector/.env connector/Dockerfile connector/README.md
      - name: Archive deployment-relevant documentation
        uses: vimtor/action-zip@v1
        with:
          files: README.md CHANGELOG.md docker-compose.yaml .env connector/.env connector/Dockerfile connector/README.md
          dest: ${{ env.ARCHIVE_FILE_NAME }}
      - name: Upload deployment-relevant documentation
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE_FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
